tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: theme_logo_image
            field:
              max_files: 1
              min_files: 1
              container: assets
              type: assets
              display: 'Logo Image'
              validate:
                - required
          -
            handle: theme_logo_svg
            field:
              type: textarea
              display: 'Logo SVG'
              validate:
                - required
